### ISSUE TITLE
表单数据量大于60k就会出现渲染卡顿

### ISSUE THREAD

**Issue by MrBigBang** [wibetter/json-editor#36]
表单数据量大于60k就会出现渲染卡顿，示例 schema 和 配置数据我邮件私发你。麻烦帮忙看下怎么优化，比如分层渲染。

**Comment by wibetter** [comment]
JSONEditor开发出来主要是用于可视化配置面板的，对于大型json数据展示起还没有做任何预设处理。目前对于较大数据块在JSONEditor渲染慢的问题还也没有想到较好的解决方法，后续有解决方案第一时间通知您。

**Comment by wibetter** [comment]
**初步解决思路**（大json数据在JSONEditor渲染很慢的问题）：
1、涉及到的json相关计算、查询、操作单独使用web workder处理，避免因为计算问题导致页面卡屏；
2、关键节点操作增加过渡效果（loading）;
3、超大数据分批渲染；

**Comment by wibetter** [comment]
此issue已建相关功能issue：https://github.com/wibetter/json-editor/issues/40
