### ISSUE TITLE
数组只有一个元素无法再删除该元素

### ISSUE THREAD

**Issue by MrBigBang** [wibetter/json-editor#44]
如果数组元素只有一个元素的时候，删除该元素会提示： '删除失败，至少保留一个数据项。‘
这个能否支持删除数组所有元素，即空数组？

**Comment by wibetter** [comment]
已完善数组子项个数的限制，默认可以删除数组最后一个子项，用户也可以通过JSONSchema给数组设置最少和最多子项。
相关代码改动点：https://github.com/wibetter/json-editor/commit/04902593ae5b29df75a1b7f31a17848b7af6fc00。
