### ISSUE TITLE
数组元素下的表单操作会报错

### ISSUE THREAD

**Issue by kevinchengchn** [wibetter/json-editor#45]
![image](https://user-images.githubusercontent.com/42643633/130047233-96b3437c-8389-44d8-8517-470edc1f7f04.png)

![image](https://user-images.githubusercontent.com/42643633/130047064-51f7f54f-9107-4af7-94bd-15e488224225.png)

**Comment by wibetter** [comment]
感谢反馈这个bug

**Comment by kevinchengchn** [comment]
@wibetter/json-utils -> keyRoute2indexRoute 方法：增加一个数组判断
      if(curJsonSchemaObj.type === 'array'){
        curJsonSchemaObj = curJsonSchemaObj.items;
      }else {
        curJsonSchemaObj = curJsonSchemaObj.properties[curKey]; // 对象类型数据引用
      }
     可能考虑不周，仅供参考

**Comment by wibetter** [comment]
问题已修复，请安装最新版本试用。
