### ISSUE TITLE
通过复制按钮得到的字段，修改其默认值JSONEditor未正常显示

### ISSUE THREAD

**Issue by kevinchengchn** [wibetter/json-editor#46]
![image](https://user-images.githubusercontent.com/42643633/130758273-ecb47e2d-3bcf-4644-b5cc-4944884e9872.png)
![image](https://user-images.githubusercontent.com/42643633/130758711-8bd0d0ba-d016-42ce-874c-8b3b8b75fb6d.png)

重现步骤：
1. field_1 设置默认值0.
2. 复制field_1 得到 field_1_2 ，修改其默认值为1，右边JSONEditor依然显示0
3. 通过+得到field_3，设置默认值为2，右边JSONEditor正常显示

**Comment by wibetter** [comment]
你好，JSONEditor中如果字段的数值不为空（undefined 或者 “”）则会优先使用json数据（mockData）中的数值，只有当json数据中的数值为空（undefined 或者 “”）才会使用schema中设置的默认值。
