### ISSUE TITLE
隐藏规则只隐藏控件，不移除jsonData相应字段

### ISSUE THREAD

**Issue by kevinchengchn** [wibetter/json-editor#48]
当field_1为true时隐藏了field_2控件，但jsonData里面的field_2字段依然存在
![image](https://user-images.githubusercontent.com/42643633/132639295-22cae828-555b-4880-a1b0-03309ac5d1e2.png)
![image](https://user-images.githubusercontent.com/42643633/132639252-da82d3ec-733d-42c4-adc5-2484c325fc43.png)
![image](https://user-images.githubusercontent.com/42643633/132639362-3ac7a70a-859b-4f31-a72f-44c69dd8e0d2.png)
![image](https://user-images.githubusercontent.com/42643633/132639470-d197de1e-8bc3-4e0d-b7b4-b86ebe8f2db8.png)

**Comment by wibetter** [comment]
感谢反馈问题，后续在全面升级中一起处理哈，请关注issues#47（https://github.com/wibetter/json-editor/issues/47）。
