### ISSUE TITLE
使用json-schema-editor时切换radio/select会报错

### ISSUE THREAD

**Issue by amberPei** [wibetter/json-editor#75]
使用json-schema-editor时，切换radio/select会报错：
Uncaught TypeError: Cannot read properties of undefined (reading 'enum')

感觉是切换之后的新schema中缺少了enum字段。

怎么解决呢？

**Comment by wibetter** [comment]
新版目前还在迭代中，还没有发布正式版本，可通过在线Demo进行试用：https://wibetter.github.io/json-editor/online-demo/5.0.0/index.html。
备注：所谓新版是指5.x以上版本。
